const emojie = [
    { emoji: '😀', name: 'Smile' },
    { emoji: '😁', name: 'Grin' },
    { emoji: '😂', name: 'Laugh' },
    { emoji: '🤣', name: 'ROFL' },
    { emoji: '😎', name: 'Cool' },
    { emoji: '😍', name: 'Heart Eyes' },
    { emoji: '😢', name: 'Cry' },
    { emoji: '😡', name: 'Angry' },
    { emoji: '🐶', name: 'Dog' },
    { emoji: '🐱', name: 'Cat' },
    { emoji: '🦁', name: 'Lion' },
    { emoji: '🐼', name: 'Panda' },
    { emoji: '🐸', name: 'Frog' },
    { emoji: '🌮', name: 'Taco' },
    { emoji: '🍕', name: 'Pizza' },
    { emoji: '🍔', name: 'Burger' },
    { emoji: '🍎', name: 'Apple' },
    { emoji: '🍌', name: 'Banana' },
    { emoji: '⚽', name: 'Soccer Ball' },
    { emoji: '🏀', name: 'Basketball' },
    { emoji: '🎸', name: 'Guitar' },
    { emoji: '🚗', name: 'Car' },
    { emoji: '✈️', name: 'Airplane' },
    { emoji: '🏠', name: 'House' },
    { emoji: '📱', name: 'Mobile Phone' },
    { emoji: '💻', name: 'Laptop' },
    { emoji: '📚', name: 'Books' },
    { emoji: '🎉', name: 'Party' },
    { emoji: '❤️', name: 'Heart' },
    { emoji: '🔥', name: 'Fire' }
  ];
  
  module.exports = emojie;